### ISSUE TITLE
SecurityConfig안에 EnableWebSecurity 어노테이션 안쪽에 Configuration이 들어있는데 EnableWebSecurity만 사용해도 되지 않을까요?

### ISSUE THREAD

**Issue by Huuuunee** [GSM-MSG/GAuth-BackEnd#178]
### Describe

![image](https://github.com/GSM-MSG/GAuth-BackEnd/assets/81404026/ea7ed31a-9a96-4381-b647-a48824c0da00)

EnableWebSecurity 어노테이션
<img width="329" alt="스크린샷 2023-06-21 오후 11 45 52" src="https://github.com/GSM-MSG/GAuth-BackEnd/assets/81404026/1241ee5f-fca3-44e5-bf4d-d2da7aff0b5f">

**Comment by esperar** [comment]
EnableWebSecurity 인터페이스의 다양한 Feature들을 사용하지 않고 있어 그저 `@Configuration`만 달아주어 사용해도 괜찮다고 생각합니다/
