### ISSUE TITLE
GenerateOauthCodeService.kt의 비정상적인 공백

### ISSUE THREAD

**Issue by baekteun** [GSM-MSG/GAuth-BackEnd#185]
### Describe

https://github.com/GSM-MSG/GAuth-BackEnd/blob/main/src/main/kotlin/com/msg/gauth/domain/oauth/service/GenerateOauthCodeService.kt#L25

**Comment by esperar** [comment]
공백 조절 했습니다

**Comment by baekteun** [comment]
이슈 링크도 해주세용
